# Generated by Django 3.2.6 on 2021-08-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='AboutMe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
