# Generated by Django 3.2.6 on 2021-08-08 16:21

import Teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_alter_teacher_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=Teacher.models.UploadTo),
        ),
    ]
