# Generated by Django 3.2.6 on 2021-08-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Name',
            new_name='Title',
        ),
    ]
