# Generated by Django 3.2.6 on 2021-08-11 22:03

import Course.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_rename_name_course_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('DateTimeSubmit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='DateTimeSubmit',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Image',
            field=models.ImageField(null=True, upload_to=Course.models.UploadTo_ImageCourse),
        ),
        migrations.AddField(
            model_name='course',
            name='LastTimeUpdated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='PreRequisites',
            field=models.CharField(default='Null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Price',
            field=models.CharField(default=10000, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='References',
            field=models.CharField(default='No Refernces', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VideoCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(upload_to=Course.models.UploadTo_VideoCourse)),
                ('DateTimeSubmit', models.DateTimeField(auto_now_add=True)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.sectioncourse')),
            ],
        ),
        migrations.AddField(
            model_name='sectioncourse',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course'),
        ),
    ]
