# Generated by Django 3.2.6 on 2021-08-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20210811_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourse',
            name='DurationVideo',
            field=models.CharField(default='2', max_length=20),
            preserve_default=False,
        ),
    ]
