# Generated by Django 3.2.6 on 2021-08-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_alter_videocourse_durationvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourse',
            name='StateVideo',
            field=models.CharField(choices=[('200', 'Ok'), ('404', 'Not Found')], default='Ok', max_length=30),
            preserve_default=False,
        ),
    ]
