# Generated by Django 3.2.6 on 2021-08-12 17:35

import Course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_videocourse_statevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='Video',
            field=models.FileField(null=True, upload_to=Course.models.UploadTo_VideoCourse),
        ),
    ]
