# Generated by Django 3.2.6 on 2021-08-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_alter_videocourse_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='StateVideo',
            field=models.CharField(choices=[('200', '200'), ('400', '400')], max_length=30),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Percent', models.CharField(max_length=5)),
                ('Time', models.CharField(max_length=15)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
            ],
        ),
    ]
