# Generated by Django 3.2.6 on 2021-08-14 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_auto_20210814_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='DateTimeSubmit',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
